#! /bin /bash
until [ `ping 8.8.8.8 -c 1 | grep -o time=` ]
do
        echo "no ping"
done
echo "ping OK"
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
#!/bin/bash

while [ `ping 8.8.8.8 -c 1 | grep -o time=` ]
do
        sleep 3
        rar a /root/log-Access/${d}$(date +%Y-%m-%d--%T).rar /var/log/apt
done
###############################################################
for i in $(sed 's|prod-||' cpbx-versions.txt | awk '{print $1":"$2}') ;do sudo docker pull $i ;done
################################################################

for i in {10..17}; do scp /etc/yum.repos.d/*.repo root@192.168.5."$i":/etc/yum.repos.d/.   کپی کردن تمام فایل های با فرمت ریپو به ای پی 10تا17
